CREATE TABLE og_list(
    id serial PRIMARY KEY,
    name text, 
    fulladdress text,	
    street text,
    municipality text,	
    categories text,
    plus_code text,
    price text,
    note text,
    amenities text,	
    hotel_class text,
    phone text,
    phones text,
    claimed	boolean,
    email text,
    social_medias text,
    review_count integer,
    average_rating DECIMAL(1,1),
    review_url text,
    google_maps_url text,
    google_knowledge_url text,	
    latitude double precision,
    longitude double precision,
    website text,
    domain text,
    opening_hours text,
    featured_image text,
    cid	text,
    place_id text,	
    kgmid text
);


ALTER TABLE og_list ALTER COLUMN average_rating TYPE DECIMAL(1,1) USING average_rating::DECIMAL(1,1); 