create table og-list(
    id serial PRIMARY KEY,
    Name text, 
    Fulladdress text,	
    Street text,
    Municipality text,	
    Categories text,
    Plus Code text,
    Price text,
    Note text,
    Amenities text,	
    Hotel Class text,
    Phone text,
    Phones text,
    Claimed	boolean,
    Email text,
    Social Medias text,
    Review Count integer,
    Average Rating smallint,
    Review URL text,
    Google Maps URL text,
    Google Knowledge URL text,	
    Latitude double precision,
    Longitude double precision,
    Website text,
    Domain text,
    Opening Hours text,
    Featured Image text,
    Cid	text,
    Place Id text,	
    Kgmid text,
)